version: "1.27"
services:
    web:
        restart: always
        build: .
        ports:
            - 3000:3000
        depends_on: 
            - mongo
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017